# Ordered by output of `jazzy --help config`

output: Documentation
clean: true
objc: false
framework_root: .
sdk: macosx
author: Simon Gaus
author_url: http://simonsapps.de
module: EventusAPI
github_url: https://github.com/Phisto/EventusAPI-Swift
github_file_prefix: https://github.com/Phisto/EventusAPI-Swift/tree/master/
skip_undocumented: false
hide_documentation_coverage: false
use_safe_filenames: true
